import { QUESTIONS } from './questions.js';
const $=s=>document.querySelector(s),tg=window.Telegram?.WebApp,now=new Date(),uid=String(tg?.initDataUnsafe?.user?.id||'guest'),prefix='365:v2:'+uid+':',today=now.toISOString().slice(0,10);
const h=now.getHours(),period=h>=5&&h<11?'morning':h<17?'day':h<22?'evening':'night';
$('#app').className='app theme-'+period;tg?.ready?.();tg?.expand?.();
let progress=Math.min(Number(localStorage.getItem(prefix+'answered-count')||0),365),saved=localStorage.getItem(prefix+'answered-'+today)==='1',index=Math.min(saved?Math.max(progress-1,0):progress,364),question=QUESTIONS[index];
function render(){const pct=progress?(progress/365*100).toFixed(progress<37?1:0)+'%':'0%';$('#progress-label').textContent=progress+' / 365 вопросов';$('#percent').textContent=pct;$('#bar').style.width=(progress/365*100)+'%';$('#number').textContent='Вопрос '+(index+1)+' из 365';$('#question').textContent=question;$('#postcard-question').textContent=question;if(saved){$('#answer-wrap').hidden=true;$('#saved').hidden=false;$('#submit').disabled=true;$('#submit').innerHTML='Ответ сохранён <span>✓</span>'}}
render();
$('#answer').addEventListener('input',e=>$('#submit').disabled=!e.target.value.trim());
$('#submit').addEventListener('click',()=>{const answer=$('#answer').value.trim();if(!answer||saved)return;progress=Math.min(progress+1,365);saved=true;localStorage.setItem(prefix+'answered-count',progress);localStorage.setItem(prefix+'answered-'+today,'1');localStorage.setItem(prefix+'answer-'+today,JSON.stringify({question,answer}));render();try{tg?.sendData(JSON.stringify({type:'daily_answer',question,answer}));tg?.HapticFeedback?.notificationOccurred('success')}catch{}});
const settingsModal=$('#settings-modal'),shareModal=$('#share-modal'),time=$('#notify-time');
function openSettings(){time.value=localStorage.getItem(prefix+'notify-time')||'09:00';settingsModal.hidden=false;selectPreset()}
function selectPreset(){document.querySelectorAll('.presets button').forEach(b=>b.classList.toggle('selected',b.textContent===time.value))}
$('#menu').onclick=$('#settings').onclick=openSettings;time.oninput=selectPreset;document.querySelectorAll('.presets button').forEach(b=>b.onclick=()=>{time.value=b.textContent;selectPreset()});
$('#save-time').onclick=()=>{localStorage.setItem(prefix+'notify-time',time.value);settingsModal.hidden=true;toast('Вопрос будет приходить в '+time.value);try{tg?.sendData(JSON.stringify({type:'notification_settings',time:time.value,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}))}catch{}};
$('#share').onclick=()=>shareModal.hidden=false;document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('.backdrop').hidden=true);document.querySelectorAll('.backdrop').forEach(b=>b.onclick=e=>{if(e.target===b)b.hidden=true});
function toast(text){const el=$('#toast');el.textContent='✓ '+text;el.hidden=false;setTimeout(()=>el.hidden=true,3000)}
function wrap(ctx,text,max){const words=text.split(' '),lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;if(ctx.measureText(next).width>max&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
$('#make-card').onclick=async()=>{const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#f8f2e3');g.addColorStop(.6,'#fffaf0');g.addColorStop(1,'#e5edd2');x.fillStyle=g;x.fillRect(0,0,1080,1350);x.textAlign='center';x.fillStyle='#1d2519';x.font='154px Georgia';x.fillText('365',540,190);x.font='36px Arial';x.fillText('вопросов к себе',540,248);x.fillStyle='#5d7b3d';x.font='bold 30px Arial';x.fillText('ВОПРОС ДНЯ',540,400);x.fillStyle='#182015';x.font='61px Georgia';let y=515;for(const line of wrap(x,question,830)){x.fillText(line,540,y);y+=82}x.fillStyle='#53604c';x.font='29px Arial';x.fillText('Один вопрос в день, чтобы лучше понимать себя',540,1120);x.fillText('и сохранять внутреннюю устойчивость',540,1164);x.fillStyle='#718c4e';x.font='bold 31px Arial';x.fillText('365 вопросов к себе',540,1260);const blob=await new Promise(r=>c.toBlob(r,'image/png')),file=new File([blob],'365-vopros-dnya.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:'365 вопросов к себе',text:'Вопрос дня — ответь на него вместе со мной.',files:[file]});shareModal.hidden=true;return}}catch(e){if(e.name==='AbortError')return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();URL.revokeObjectURL(url);shareModal.hidden=true;toast('Открытка сохранена')};
